#!/usr/bin/env php
<?php
require_once __DIR__.'/../vendor/autoload.php';

set_time_limit(0);

// Commands
require_once __DIR__.'/commands/IcaHarvestCommand.php';

// Utils
//require_once __DIR__.'/utils/VoteSmart.php';

use \Comm\Harvest\Command\IcaHarvestCommand;
//use Comm\VoteSmart\Command\GrabFromVotesmartCommand;
//use Comm\VoteSmart\Command\CompileVotesmartChunksCommand;
//use Comm\Misc\Command\ExportTwitterCommand;
//use Comm\Misc\Command\TwitterCsvCommand;

use Symfony\Component\Console\Application;


$application = new Application("UKCOMM NCA/ICA Harvester");
$application->add(new IcaHarvestCommand);

$application->run();
